config/routes.rb
Blogr::Engine.routes.draw do

  resources :posts
  resources :categories
  resources :tags
  resources :users
  resources :comments

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  resources :sessions, only: [:index, :create]

  root to: "dashboard#index"

end

app/models/blogr/categories_post.rb
module Blogr
  class CategoriesPost < ActiveRecord::Base
    validates_uniqueness_of :category_id, :scope => [:post_id]
  end
end

app/models/blogr/category.rb
module Blogr
  class Category < ActiveRecord::Base

    has_many :posts, class_name: "Blogr::Post"

    before_validation { self.permalink = self.title.parameterize if self.title }

    validates_uniqueness_of :title, :permalink
    validates_presence_of :title, :permalink

    def to_param
      permalink
    end

  end
end

app/models/blogr/comment.rb
module Blogr
  class Comment < ActiveRecord::Base

    belongs_to :post, class_name: "Blogr::Post"
    belongs_to :user, class_name: "Blogr::User"

    validates_presence_of :post_id, :content

  end
end

app/models/blogr/image.rb
module Blogr
  class Image < ActiveRecord::Base
    
    belongs_to :post, class_name: "Blogr::Post"

    validates :file, presence: true

    # has_attached_file :file, :styles => { medium: "500#", thumb: "198x160>", big: "970x"  }, :default_url => "/images/:style/missing.png"

  end
end

app/models/blogr/post.rb
include Blogr::PostsHelper

module Blogr
  class Post < ActiveRecord::Base

    belongs_to :category, class_name: "Blogr::Category"
    belongs_to :user, class_name: "Blogr::User"
    has_many :taggings, class_name: "Blogr::Tagging"
    has_many :tags, through: :taggings, class_name: "Blogr::Tag"
    has_many :comments, class_name: "Blogr::Comment"

    before_validation { self.permalink = title.parameterize if self.permalink.nil? }

    validates_uniqueness_of :permalink
    validates_presence_of :title, :permalink, :content, :user_id

    mount_uploader :post_image, PostImageUploader

    scope :published, -> { where "published = ? AND published_at <= ?", true, Time.now.to_s }
    scope :draft,    -> { where published: false }

    def to_param
      permalink
    end

    
    # The date parsed as 04 November 2013
    #
    # @return [String]
    def date_parsed
      published && published_at.present? ? published_at.strftime("%d %B %Y") : ""
    end

    # The Markdown content rendered to HTML
    #
    # @return [String]
    def content_rendered
      markdown(content).html_safe
    end

    def self.tagged_with(name)
      Blogr::Tag.find_by_name!(name).posts
    end

    def self.tag_counts
      Blogr::Tag.select(
        "#{Blogr::Tag.table_name}.*, COUNT(#{Blogr::Tagging.table_name}.tag_id) AS count"
      ).joins(:taggings).group("#{Blogr::Tagging.table_name}.tag_id")
    end

    def tag_list
      tags.map(&:name).join(", ")
    end

    def tag_list=(names)
      self.tags = names.split(",").map do |n|
        Blogr::Tag.where(name: n.strip).first_or_create!
      end
    end

  end
end

app/models/blogr/tag.rb
module Blogr
  class Tag < ActiveRecord::Base

  	has_many :taggings, class_name: "Blogr::Tagging"
  	has_many :posts, through: :taggings, class_name: "Blogr::Post"

  	before_validation { self.permalink = name.parameterize }

  	def to_param
  		permalink
  	end

  end
end

app/models/blogr/tagging.rb
module Blogr
  class Tagging < ActiveRecord::Base

    belongs_to :tag, class_name: "Blogr::Tag"
    belongs_to :post, class_name: "Blogr::Post"

  end
end

app/models/blogr/user.rb
module Blogr
  class User < ActiveRecord::Base

  	has_secure_password

  	validates_presence_of :first_name, :last_name, :username, :email, :password
    has_many :posts, class_name: "Blogr::Post"

  	def name
  		[first_name, last_name].join(" ")	
  	end

  end
end

app/controllers/blogr/application_controller.rb
module Blogr
  class ApplicationController < ActionController::Base

  	layout "blogr/application"

  	before_filter :authorize

  	private

  	helper_method :current_blogr_user
  	helper_method :authorize

		def current_blogr_user
	    if session[:user_id]
	      @current_blogr_user ||= User.find(session[:user_id])
	    end
	    rescue ActiveRecord::RecordNotFound
		end

	  def authorize
	    if current_blogr_user.nil?
	      redirect_to login_path
	    end
	  end

  end
end

app/controllers/blogr/categories_controller.rb
require_dependency "blogr/application_controller"

module Blogr
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    def index
      @categories = Category.all
      @title = "Categories"
    end

    def show
      @title = @category.title
    end

    def new
      @category = Category.new
      @title = "New Category"
    end

    def edit
      @title = "Editing '#{@category.title}'"
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to category_path(@category), notice: 'Category was successfully created.'
      else
        render action: 'new'
      end
    end

    def update
      if @category.update(category_params)
        redirect_to category_path(@category), notice: 'Category was successfully updated.'
      else
        render action: 'edit'
      end
    end

    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find_by(permalink: params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def category_params
        params.require(:category).permit(:title, :description)
      end
  end
end

app/controllers/blogr/comments_controller.rb
require_dependency "blogr/application_controller"

module Blogr
  class CommentsController < ApplicationController

  	before_action :set_comment, only: [:show, :edit, :update, :destroy]

  	def index
  		@title = "Comments"
  		@comments = Blogr::Comment.all
  	end

  	def show
			@title = "Comment ##{@comment.id}"
		end

		def new
			@comment = Comment.new
			@title = "New Comment"
		end

		def edit
			@title = "Editing Comment by '#{@comment.author_name}'"
		end

		def create
			@comment = Comment.new(tag_params)

			if @comment.save
				redirect_to @comment, notice: 'Comment was successfully created.'
			else
				render action: 'new'
			end
		end

		def update
			if @comment.update(tag_params)
				redirect_to @comment, notice: 'Comment was successfully updated.'
			else
				render action: 'edit'
			end
		end

		def destroy
			@comment.destroy
			redirect_to comments_path, notice: 'Comment was successfully destroyed.'
		end

		private
			# Use callbacks to share common setup or constraints between actions.
			def set_comment
				@comment = Comment.find(params[:id])
			end

			def comment_params
				params.require(:comment).permit(:content, :author_name, :author_email)
			end

  end
end

app/controllers/blogr/dashboard_controller.rb
module Blogr
  class DashboardController < ApplicationController

    def index
			@title = "Dashboard"
    end

  end
end

app/controllers/blogr/posts_controller.rb
require_dependency "blogr/application_controller"

module Blogr
	class PostsController < ApplicationController

		before_action :set_post, only: [:show, :edit, :update, :destroy]

		def index
			pub = params[:published] == "false" ? false : true
			@posts = Post.order(published_at: :desc).where(published: pub)
			@title = "Posts"
			if pub
				@subtitle = "Showing Published Posts"
			else
				@subtitle = "Showing Draft Posts"
			end
		end

		def show
			@title = @post.title
		end

		def new
			@post = Post.new
			@title = "New Post"
		end

		def edit
			if params[:delete_image]
				Image.find(params[:delete_image]).try :destroy
			end
			@title = "Editing '#{@post.title}'"
		end

		def create
			@post = current_blogr_user.posts.build(post_params)
			if @post.save
				redirect_to @post, notice: "Post was successfully created"
			else
				render action: "new"
			end
		end

		def update

			if @post.update(post_params)
				redirect_to @post, notice: "Post was successfully updated"
			else
				render action: "edit"
			end
		end

		def destroy
			@post.destroy
			redirect_to posts_url, notice: "Post was successfully destroyed"
		end

		private

		def set_post
			@post = Post.find_by_permalink!(params[:id])
		end

		def post_params
			params.require(:post).permit(:title, :category_id, :permalink, :content, :tag_list, :post_image, :published, :published_at)
		end

	end
end

app/controllers/blogr/sessions_controller.rb
require_dependency "blogr/application_controller"

module Blogr
  class SessionsController < ApplicationController

  	layout "blogr/login"

  	before_filter :authorize, except: [:new, :create]

    def index
    	redirect_to login_path		
    end
    
    def new
    	if current_blogr_user
    		redirect_to root_path
    		flash[:error] = "You are already logged in"
    	end

    	@title = "Login"
    	session[:return_to] = params[:return_to] if params[:return_to]
    end

    def create
    	user = User.find_by_username(params[:username]) || User.find_by_email(params[:username])
    	if user && user.authenticate(params[:password])
    		session[:user_id] = user.id
    		redirect_to root_path, notice: "Welcome back #{user.first_name}, time to get blogging!"
    	else
    		flash[:error] = "Username or password is invalid"
    		render "new"
    	end
    end

    def destroy
    	session[:user_id] = nil
    	redirect_to login_path, :notice => "Logged out!"
    end

  end
end

app/controllers/blogr/tags_controller.rb
require_dependency "blogr/application_controller"

module Blogr
	class TagsController < ApplicationController
	
		before_action :set_tag, only: [:show, :edit, :update, :destroy]

		def index
			@tags = Tag.all
			@title = "Tags"
		end

		def show
			@title = @tag.name
		end

		def new
			@tag = Tag.new
			@title = "New Tag"
		end

		def edit
			@title = "Editing '#{@tag.name}'"
		end

		def create
			@tag = Tag.new(tag_params)

			if @tag.save
				redirect_to tags_path, notice: 'Tag was successfully created.'
			else
				render action: 'new'
			end
		end

		def update
			if @tag.update(tag_params)
				redirect_to tags_path, notice: 'Tag was successfully updated.'
			else
				render action: 'edit'
			end
		end

		def destroy
			@tag.destroy
			redirect_to categories_url, notice: 'Tag was successfully destroyed.'
		end

		private
			# Use callbacks to share common setup or constraints between actions.
			def set_tag
				@tag = Tag.find_by(permalink: params[:id])
			end

			def tag_params
				params.require(:tag).permit(:name, :permalink)
			end

	end
end

app/controllers/blogr/users_controller.rb
require_dependency "blogr/application_controller"

module Blogr
  class UsersController < ApplicationController

  	before_action :set_user, only: [:edit, :show, :update, :destroy]

		def index
			@title = "Users"
			@users = Blogr::User.all
		end

		def show
			@title = @user.username
			@posts = @user.posts
		end

		def new
			@title = "New User"
			@user = User.new
		end

		def edit
			@title = "Editing '#{@user.username}'"
		end

		def create
			@user = User.new(user_params)

			if @user.save
				redirect_to users_path, notice: "User was successfully created"
			else
				render action: "new"
			end
		end

		def update
			if @user.update(user_params)
				redirect_to users_path, notice: "User was successfully updated"
			else
				render action: "edit"
			end
		end

		def destroy
			@user.destroy
			redirect_to users_path, notice: "User was successfully destroyed"
		end

		private

		def set_user
			@user = User.find(params[:id])
		end

		def user_params
			params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
		end

  end
end

app/helpers/blogr/application_helper.rb
module Blogr
  module ApplicationHelper
  end
end

app/helpers/blogr/posts_helper.rb
require "redcarpet"
require "pygments"

module Blogr
  module PostsHelper

    def check_category post_object, category_object
      attr = {}
      if post_object.categories.pluck(:id).include?(category_object.id)
        attr[:checked] = 'checked'
      end

      return attr
    end

    def markdown(text)
      redcarpet = Redcarpet::Markdown.new(HTMLwithPygments, :fenced_code_blocks => true, :autolink => true, :space_after_headers => true, :underline => true, :highlight => true)
      redcarpet.render(text)
    end

    class HTMLwithPygments < Redcarpet::Render::HTML
      def header(text, header_level)
        "<h#{header_level + 1}>#{text}</h#{header_level + 1}>"
      end

      def block_code(code, language)
        title = nil
        code.gsub!(/\A\:\:(.*)$/) { title = $1 ; nil }
        String.new.tap do |s|
          s << "<p class='codeTitle'>#{title}</p>" if title
          s << Pygments.highlight(code, :lexer => language)
        end
      rescue 
        "<div class='highlight'><pre>#{code}</pre></div>"
      end
    end

  end
end

app/helpers/blogr/sessions_helper.rb
module Blogr
  module SessionsHelper
  end
end

app/helpers/blogr/tags_helper.rb
module Blogr
  module TagsHelper
  end
end

app/views/layouts/blogr/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogr</title>
    <%= stylesheet_link_tag    "blogr/application", media: "all" %>
    <%= javascript_include_tag "blogr/application" %>
    <%= csrf_meta_tags %>

    <%= yield :before %>

  </head>
  <body>

    <%#= render 'layouts/blogr/menu' %>


    <nav class="sidebar" style="width: 200px;
background: #40454D;
position: fixed;
top: 0;
bottom: 0;
">
      <h1><%= link_to "Blogr", root_path%></h1>
      <ul>
        <li> <%= link_to 'Posts', posts_path %> </li>
        <ul>
          <li> <%= link_to 'Published', posts_path %> </li>
          <li> <%= link_to 'Drafts', posts_path %> </li>
        </ul>
        <li> <%= link_to 'Categories', categories_path %> </li>
        <li> <%= link_to 'Stats', categories_path %> </li>
      </ul>
    </nav>


    <div class="container" style="padding-left: 200px;">
      <%= yield %>
    </div> <!-- .container -->

    <%= yield :after %>
  </body>
</html>

app/views/layouts/blogr/application.html.haml
!!!
%html{lang: "en"}
	%head
		%meta{charset: "utf-8"}/
		%meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
		%title #{@title} - #{Blogr.config.name}
		= stylesheet_link_tag    "//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css"
		= stylesheet_link_tag    "blogr/application"
		= javascript_include_tag "blogr/application"
		= csrf_meta_tags

	%body{class: "blogr #{controller.controller_name} #{controller.action_name}"}

		%section.sidebar
			.logo
				%h1= link_to "#{Blogr.config.name} ", root_url
				.version= link_to "v#{Blogr::VERSION}", "https://github.com/blogr/engine"
			.user
				= gravatar(current_blogr_user.email, {size: 50, class: "avatar"})
				.name= current_blogr_user.name
				%small.logout= link_to "Log Out", logout_path
			%ul.nav
				%li= link_to raw("#{content_tag(:i, '', class: 'batch batch-arrow-left')} View Site"), main_app.root_url
				%li= link_to raw("#{content_tag(:i, '', class: 'batch batch-document')} Blogr Documentation"), "https://docs.voupe.com/blogr/"
			%ul.nav
				= active_link_to raw("#{content_tag(:i, '', class: 'batch batch-home')} Dashboard"), root_path, active: [["dashboard"], ["index"]], wrap_tag: :li
				= active_link_to raw("#{content_tag(:i, '', class: 'batch batch-list')} Posts"), posts_path, wrap_tag: :li
				= active_link_to raw("#{content_tag(:i, '', class: 'batch batch-tag-alt')} Categories"), categories_path, wrap_tag: :li
				= active_link_to raw("#{content_tag(:i, '', class: 'batch batch-tag')} Tags"), tags_path, wrap_tag: :li
				= active_link_to raw("#{content_tag(:i, '', class: 'batch batch-users')} Users"), users_path, wrap_tag: :li
				= active_link_to raw("#{content_tag(:i, '', class: 'batch batch-speech-chat-left')} Comments"), comments_path, wrap_tag: :li

		%section.main
			%header
				%span.icon
				%h3 #{@title} <small>#{@subtitle}</small>
				.links.pull-right= yield :links

			.messages= render "blogr/shared/messages"
			
			.content= yield

			%footer
				%p.pull-right Powered by #{link_to "Blogr", "https://github.com/blogr/engine"} v#{Blogr::VERSION}
				%p &copy; #{Blogr.config.name} #{Time.now.year}

	- if Rails.env.development?
		<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>

app/views/layouts/blogr/login.html.haml
!!!
%html{lang: "en"}
	%head
		%meta{charset: "utf-8"}/
		%meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
		%title Login - #{Blogr.config.name}
		= stylesheet_link_tag    "//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css"
		= stylesheet_link_tag    "blogr/application"
		= javascript_include_tag "blogr/application"
		= csrf_meta_tags

	%body{class: "blogr login"}
		= yield

	- if Rails.env.development?
		<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>